
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: checkbox_checked_icon&16
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Edge 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_checkbox_checked_icon16[32] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙██████∙∙∙∙∙∙∙
    // ∙∙██████∙∙∙∙∙∙∙∙
    // ∙██∙∙∙∙∙∙∙∙∙██∙∙
    // ∙██∙∙∙∙∙∙∙∙∙██∙∙
    // ∙██∙∙∙∙∙∙∙████∙∙
    // ∙██∙∙███∙∙███∙∙∙
    // ∙██∙████████∙∙∙∙
    // ∙██∙∙███████∙∙∙█
    // ∙██∙∙█████∙∙∙∙██
    // ∙██∙∙∙∙███∙∙∙∙██
    // ∙██∙∙∙∙∙█∙∙∙∙∙██
    // ∙██∙∙∙∙∙∙∙∙∙∙∙██
    // ∙██∙∙∙∙∙∙∙∙∙∙███
    // ∙███████████████
    // ∙∙█████████████∙
    0x00, 0x00, 
    0x1f, 0x80, 
    0x3f, 0x00, 
    0x60, 0x0c, 
    0x60, 0x0c, 
    0x60, 0x3c, 
    0x67, 0x38, 
    0x6f, 0xf0, 
    0x67, 0xf1, 
    0x67, 0xc3, 
    0x61, 0xc3, 
    0x60, 0x83, 
    0x60, 0x03, 
    0x60, 0x07, 
    0x7f, 0xff, 
    0x3f, 0xfe
};
const tImage checkbox_checked_icon16 = { image_data_checkbox_checked_icon16, 16, 16,
    8 };

