// automatically generated by the FlatBuffers compiler, do not modify

export enum eRgbwPwmCommand {
  TOGGLE = 0,
  ON = 1,
  OFF = 2,
  CHANGE_HUE_0_360 = 3,
  CHANGE_SATURATION_0_1 = 4,
  CHANGE_VALUE_0_1 = 5,
  CHANGE_R_0_255 = 6,
  CHANGE_G_0_255 = 7,
  CHANGE_B_0_255 = 8,
  CHANGE_WWCW_BRIGHTNESS_0_1 = 9,
  CHANGE_WWCW_RATIO_0_1 = 10
}
