"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.unionListTouCommand = exports.unionTouCommand = exports.uCommand = void 0;
var t_blind_command_js_1 = require("../../sensact/comm/t-blind-command.js");
var t_on_off_command_js_1 = require("../../sensact/comm/t-on-off-command.js");
var t_rgbw_pwm_command_js_1 = require("../../sensact/comm/t-rgbw-pwm-command.js");
var t_single_pwm_command_js_1 = require("../../sensact/comm/t-single-pwm-command.js");
var uCommand;
(function (uCommand) {
    uCommand[uCommand["NONE"] = 0] = "NONE";
    uCommand[uCommand["tBlindCommand"] = 1] = "tBlindCommand";
    uCommand[uCommand["tSinglePwmCommand"] = 2] = "tSinglePwmCommand";
    uCommand[uCommand["tOnOffCommand"] = 3] = "tOnOffCommand";
    uCommand[uCommand["tRgbwPwmCommand"] = 4] = "tRgbwPwmCommand";
})(uCommand = exports.uCommand || (exports.uCommand = {}));
function unionTouCommand(type, accessor) {
    switch (uCommand[type]) {
        case 'NONE': return null;
        case 'tBlindCommand': return accessor(new t_blind_command_js_1.tBlindCommand());
        case 'tSinglePwmCommand': return accessor(new t_single_pwm_command_js_1.tSinglePwmCommand());
        case 'tOnOffCommand': return accessor(new t_on_off_command_js_1.tOnOffCommand());
        case 'tRgbwPwmCommand': return accessor(new t_rgbw_pwm_command_js_1.tRgbwPwmCommand());
        default: return null;
    }
}
exports.unionTouCommand = unionTouCommand;
function unionListTouCommand(type, accessor, index) {
    switch (uCommand[type]) {
        case 'NONE': return null;
        case 'tBlindCommand': return accessor(index, new t_blind_command_js_1.tBlindCommand());
        case 'tSinglePwmCommand': return accessor(index, new t_single_pwm_command_js_1.tSinglePwmCommand());
        case 'tOnOffCommand': return accessor(index, new t_on_off_command_js_1.tOnOffCommand());
        case 'tRgbwPwmCommand': return accessor(index, new t_rgbw_pwm_command_js_1.tRgbwPwmCommand());
        default: return null;
    }
}
exports.unionListTouCommand = unionListTouCommand;
