"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.unionListTouState = exports.unionTouState = exports.uState = void 0;
var t_blind_state_js_1 = require("../../sensact/comm/t-blind-state.js");
var t_on_off_state_js_1 = require("../../sensact/comm/t-on-off-state.js");
var t_rgbw_pwm_state_js_1 = require("../../sensact/comm/t-rgbw-pwm-state.js");
var t_single_pwm_state_js_1 = require("../../sensact/comm/t-single-pwm-state.js");
var uState;
(function (uState) {
    uState[uState["NONE"] = 0] = "NONE";
    uState[uState["tBlindState"] = 1] = "tBlindState";
    uState[uState["tSinglePwmState"] = 2] = "tSinglePwmState";
    uState[uState["tOnOffState"] = 3] = "tOnOffState";
    uState[uState["tRgbwPwmState"] = 4] = "tRgbwPwmState";
})(uState = exports.uState || (exports.uState = {}));
function unionTouState(type, accessor) {
    switch (uState[type]) {
        case 'NONE': return null;
        case 'tBlindState': return accessor(new t_blind_state_js_1.tBlindState());
        case 'tSinglePwmState': return accessor(new t_single_pwm_state_js_1.tSinglePwmState());
        case 'tOnOffState': return accessor(new t_on_off_state_js_1.tOnOffState());
        case 'tRgbwPwmState': return accessor(new t_rgbw_pwm_state_js_1.tRgbwPwmState());
        default: return null;
    }
}
exports.unionTouState = unionTouState;
function unionListTouState(type, accessor, index) {
    switch (uState[type]) {
        case 'NONE': return null;
        case 'tBlindState': return accessor(index, new t_blind_state_js_1.tBlindState());
        case 'tSinglePwmState': return accessor(index, new t_single_pwm_state_js_1.tSinglePwmState());
        case 'tOnOffState': return accessor(index, new t_on_off_state_js_1.tOnOffState());
        case 'tRgbwPwmState': return accessor(index, new t_rgbw_pwm_state_js_1.tRgbwPwmState());
        default: return null;
    }
}
exports.unionListTouState = unionListTouState;
