// automatically generated by the FlatBuffers compiler, do not modify

export enum eRelayInterlockMode {
  R1_UP__R2_DOWN = 0,
  R1_DOWN__R2_UP = 1,
  R1_POWER__R2_UP = 2,
  R1_POWER__R2_DOWN = 3,
  R1_UP__R2_POWER = 4,
  R1_DOWN__R2_POWER = 5
}
