// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ui_event_scrHome( lv_event_t * e);
lv_obj_t *ui_scrHome;
void ui_event_sldVolume( lv_event_t * e);
lv_obj_t *ui_sldVolume;
lv_obj_t *ui_lblSldVolume;
lv_obj_t *ui_lblEthernetIP;
void ui_event_btnNext( lv_event_t * e);
lv_obj_t *ui_btnNext;
lv_obj_t *ui_lblBtnNext;
lv_obj_t *ui_pnlWifiConnect;
lv_obj_t *ui_lblWifiIP;
lv_obj_t *ui_pnlEthernetConnect;
lv_obj_t *ui_lblHeapX;
lv_obj_t *ui_lblErrX;
lv_obj_t *ui_lblHeap;
lv_obj_t *ui_lblError;
lv_obj_t *ui_lblCanIdX;
lv_obj_t *ui_lblCanId;
lv_obj_t *ui_Label1;
void ui_event_scrSettings( lv_event_t * e);
lv_obj_t *ui_scrSettings;
void ui_event_btnPrev( lv_event_t * e);
lv_obj_t *ui_btnPrev;
lv_obj_t *ui_lblBtnPrev;
lv_obj_t *ui_lblTime;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_scrHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      setGroupscrHome( e );
}
}
void ui_event_sldVolume( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      onVolumeChanged( e );
}
}
void ui_event_btnNext( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_scrSettings, LV_SCR_LOAD_ANIM_NONE, 500, 0);
}
}
void ui_event_scrSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      setGroupscrSettings( e );
}
}
void ui_event_btnPrev( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_scrHome, LV_SCR_LOAD_ANIM_NONE, 500, 0);
}
}

///////////////////// SCREENS ////////////////////
void ui_scrHome_screen_init(void)
{
ui_scrHome = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sldVolume = lv_slider_create(ui_scrHome);
lv_obj_set_width( ui_sldVolume, 115);
lv_obj_set_height( ui_sldVolume, 10);
lv_obj_set_x( ui_sldVolume, 10 );
lv_obj_set_y( ui_sldVolume, 60 );

ui_lblSldVolume = lv_label_create(ui_sldVolume);
lv_obj_set_width( ui_lblSldVolume, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblSldVolume, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblSldVolume, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblSldVolume,"Volume");

ui_lblEthernetIP = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblEthernetIP, 115);
lv_obj_set_height( ui_lblEthernetIP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEthernetIP, 20 );
lv_obj_set_y( ui_lblEthernetIP, 0 );
lv_label_set_text(ui_lblEthernetIP,"192.168.x.y");

ui_btnNext = lv_btn_create(ui_scrHome);
lv_obj_set_width( ui_btnNext, 60);
lv_obj_set_height( ui_btnNext, 25);
lv_obj_set_align( ui_btnNext, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_btnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnNext, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblBtnNext = lv_label_create(ui_btnNext);
lv_obj_set_width( ui_lblBtnNext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblBtnNext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblBtnNext, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblBtnNext,"Next");

ui_pnlWifiConnect = lv_obj_create(ui_scrHome);
lv_obj_set_width( ui_pnlWifiConnect, 20);
lv_obj_set_height( ui_pnlWifiConnect, 20);
lv_obj_set_x( ui_pnlWifiConnect, 0 );
lv_obj_set_y( ui_pnlWifiConnect, 30 );
lv_obj_clear_flag( ui_pnlWifiConnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblWifiIP = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblWifiIP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblWifiIP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblWifiIP, 20 );
lv_obj_set_y( ui_lblWifiIP, 30 );
lv_label_set_text(ui_lblWifiIP,"192.168.x.y");

ui_pnlEthernetConnect = lv_obj_create(ui_scrHome);
lv_obj_set_width( ui_pnlEthernetConnect, 20);
lv_obj_set_height( ui_pnlEthernetConnect, 20);
lv_obj_clear_flag( ui_pnlEthernetConnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblHeapX = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblHeapX, 46);
lv_obj_set_height( ui_lblHeapX, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblHeapX, 0 );
lv_obj_set_y( ui_lblHeapX, 90 );
lv_label_set_text(ui_lblHeapX,"Heap:");

ui_lblErrX = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblErrX, 28);
lv_obj_set_height( ui_lblErrX, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblErrX, 0 );
lv_obj_set_y( ui_lblErrX, 120 );
lv_label_set_text(ui_lblErrX,"Err:");

ui_lblHeap = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblHeap, 85);
lv_obj_set_height( ui_lblHeap, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblHeap, 50 );
lv_obj_set_y( ui_lblHeap, 90 );

ui_lblError = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblError, 85);
lv_obj_set_height( ui_lblError, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblError, 50 );
lv_obj_set_y( ui_lblError, 120 );

ui_lblCanIdX = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblCanIdX, 45);
lv_obj_set_height( ui_lblCanIdX, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblCanIdX, 0 );
lv_obj_set_y( ui_lblCanIdX, 150 );
lv_label_set_text(ui_lblCanIdX,"CanId:");

ui_lblCanId = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_lblCanId, 85);
lv_obj_set_height( ui_lblCanId, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblCanId, 50 );
lv_obj_set_y( ui_lblCanId, 150 );

ui_Label1 = lv_label_create(ui_scrHome);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 142 );
lv_obj_set_y( ui_Label1, -38 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_sldVolume, ui_event_sldVolume, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnNext, ui_event_btnNext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_scrHome, ui_event_scrHome, LV_EVENT_ALL, NULL);

}
void ui_scrSettings_screen_init(void)
{
ui_scrSettings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnPrev = lv_btn_create(ui_scrSettings);
lv_obj_set_width( ui_btnPrev, 60);
lv_obj_set_height( ui_btnPrev, 25);
lv_obj_set_x( ui_btnPrev, 1 );
lv_obj_set_y( ui_btnPrev, 0 );
lv_obj_set_align( ui_btnPrev, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_btnPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPrev, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblBtnPrev = lv_label_create(ui_btnPrev);
lv_obj_set_width( ui_lblBtnPrev, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblBtnPrev, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblBtnPrev, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblBtnPrev,"Prev");

ui_lblTime = lv_label_create(ui_scrSettings);
lv_obj_set_width( ui_lblTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTime,"23:59:59");

lv_obj_add_event_cb(ui_btnPrev, ui_event_btnPrev, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_scrSettings, ui_event_scrSettings, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_scrHome_screen_init();
ui_scrSettings_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_scrHome);
}
