// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void ui_event_scrHome( lv_event_t * e);
extern lv_obj_t *ui_scrHome;
void ui_event_sldVolume( lv_event_t * e);
extern lv_obj_t *ui_sldVolume;
extern lv_obj_t *ui_lblSldVolume;
extern lv_obj_t *ui_lblEthernetIP;
void ui_event_btnNext( lv_event_t * e);
extern lv_obj_t *ui_btnNext;
extern lv_obj_t *ui_lblBtnNext;
extern lv_obj_t *ui_pnlWifiConnect;
extern lv_obj_t *ui_lblWifiIP;
extern lv_obj_t *ui_pnlEthernetConnect;
extern lv_obj_t *ui_lblHeapX;
extern lv_obj_t *ui_lblErrX;
extern lv_obj_t *ui_lblHeap;
extern lv_obj_t *ui_lblError;
extern lv_obj_t *ui_lblCanIdX;
extern lv_obj_t *ui_lblCanId;
extern lv_obj_t *ui_Label1;
void ui_event_scrSettings( lv_event_t * e);
extern lv_obj_t *ui_scrSettings;
void ui_event_btnPrev( lv_event_t * e);
extern lv_obj_t *ui_btnPrev;
extern lv_obj_t *ui_lblBtnPrev;
extern lv_obj_t *ui_lblTime;
extern lv_obj_t *ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
