// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include <cstdio>
#include <hal.hh>
extern sensact::hal::iHAL* halobj;
extern lv_group_t * groupHome;
extern lv_group_t * groupSettings;
extern lv_indev_t * encoder_indev;

void setGroupscrHome(lv_event_t * e)
{
	if(!encoder_indev || !groupHome) return;
	lv_indev_set_group(encoder_indev, groupHome);
}

void setGroupscrSettings(lv_event_t * e)
{
	lv_indev_set_group(encoder_indev, groupSettings);
}

void onVolumeChanged(lv_event_t * e)
{
		halobj->SetAmplifierVolume(2.55*lv_slider_get_value(ui_sldVolume));
}
