#pragma once

#ifdef STM32F1
#define CONSOLE_USART USART1
#define MP3_BELL_USART USART1
#define CONSOLE_USART_IRQn USART1_IRQn
#define UART_BUFFER_SIZE 100
#define CAN CAN1
#define CAN_PRESCALER 18
#define DCF77_PORT GPIOC
#define DCF77_PIN GPIO_PIN_4
#endif
#ifdef STM32F4
#define CONSOLE_UART USART3
#define MP3_BELL_UART UART4
#define CONSOLE_USART_IRQn USART3_IRQn
#define UART_BUFFER_SIZE 100
#define CAN CAN2
#define CAN_PRESCALER 21
#define DCF77_PORT GPIOC
#define DCF77_PIN GPIO_PIN_4
#endif
