// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Klli.Sensact.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class APPLICATION_CPP : CommonFileHeader
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
 RenderHeader("Application.cpp", "autogen", version, "Short", "Details"); 
            
            #line default
            #line hidden
            this.Write("\r\n#include <cApplication.h>\r\n#include <cLog.h>\r\n#include <cModel.h>\r\n#include <cM" +
                    "aster.h>\r\n\r\nnamespace sensact {\r\nvoid cApplication::OnCommand(eCommandType cmd, " +
                    "const uint8_t * const payload,\r\n\t\tuint8_t payloadLength, Time_t now) {\r\n\tswitch(" +
                    "cmd)\r\n\t{\r\n");
            
            #line 18 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandParseImplementation));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tdefault:break;\r\n\t}\r\n\t(void)payloadLength;\r\n\treturn;\r\n}\r\n\r\n");
            
            #line 25 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandCreateImplementation));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 27 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandEmptyHandlerImplementation));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n} /* namespace sensact */\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
