// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Klli.Sensact.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class APPLICATION_CPP : CommonFileHeader
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
 RenderHeader("Application.cpp", "autogen", version, "Short", "Details"); 
            
            #line default
            #line hidden
            this.Write("\r\n#include <cApplication.h>\r\n#include <cLog.h>\r\n#include <cModel.h>\r\n\r\nnamespace " +
                    "sensact {\r\nvoid cApplication::OnCommand(eCommandType cmd, uint8_t *payload,\r\n\t\tu" +
                    "int8_t payloadLength, Time_t now) {\r\n\tswitch(cmd)\r\n\t{\r\n");
            
            #line 17 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
foreach(CommandType ct in Commands){ 
            
            #line default
            #line hidden
            this.Write("\t\tcase eCommandType::");
            
            #line 18 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Convert.ToString(ct)));
            
            #line default
            #line hidden
            this.Write(": On");
            
            #line 18 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Convert.ToString(ct)));
            
            #line default
            #line hidden
            this.Write("Command(payload, payloadLength, now); break;\r\n");
            
            #line 19 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\tcase eCommandType::CNT:break;\r\n\t}\r\n\treturn;\r\n}\r\n");
            
            #line 24 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
foreach(CommandType ct in Commands){ 
            
            #line default
            #line hidden
            this.Write("void cApplication::On");
            
            #line 25 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Convert.ToString(ct)));
            
            #line default
            #line hidden
            this.Write("Command(uint8_t *payload,\r\n\t\tuint8_t payloadLength, Time_t now)\r\n{\r\n\t(void)(paylo" +
                    "ad);\r\n\t(void)(payloadLength);\r\n\t(void)(now);\r\n\tLOGE(\"Application %s does not sup" +
                    "port Command ");
            
            #line 31 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Convert.ToString(ct)));
            
            #line default
            #line hidden
            this.Write("\", Name);\r\n}\r\n");
            
            #line 33 "C:\sensact\configware\Klli.Sensact.Config\Templates\APPLICATION_CPP.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n} /* namespace sensact */\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
