// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Klli.Sensact.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class HC_COMMANDANDEVENTTYPES_H : CommonFileHeader
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
 RenderHeader("CommandAndEventTypes", "autogen", version, "Short", "Details"); 
            
            #line default
            #line hidden
            this.Write("#pragma once\r\n#include <inttypes.h>\r\nnamespace sensact{\r\nenum struct eCommandType" +
                    ":uint8_t{\r\n\t");
            
            #line 11 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
 foreach (string s in CommandTypes){ 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 12 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s));
            
            #line default
            #line hidden
            this.Write(",\r\n    ");
            
            #line 13 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    CNT\r\n};\r\n\r\nenum struct eEventType:uint8_t{\r\n\t");
            
            #line 18 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
 foreach (string s in EventTypes){ 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 19 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s));
            
            #line default
            #line hidden
            this.Write(",\r\n    ");
            
            #line 20 "C:\Users\klaus\OneDrive\sensact\configware\Klli.Sensact.Config\Templates\HC_COMMANDANDEVENTTYPES_H.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    CNT\r\n};\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
