// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Klli.Sensact.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class HC_MODEL_CPP : CommonFileHeader
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
 RenderHeader("hc_model.cpp", "autogen", version, ModelReference, "All params and details about the home model"); 
            
            #line default
            #line hidden
            this.Write("\r\n//Known Nodes are\r\n");
            
            #line 9 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"

foreach (ModelCppItem i in Items)
{

            
            #line default
            #line hidden
            this.Write("//NODE_");
            
            #line 13 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.NodeId));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n#include \"common.h\"\r\n#include \"cModel.h\"\r\n\r\nusing namespace std;\r\n\r\nnamespace s" +
                    "ensact {\r\n\r\nconst char * const MODEL::ApplicationNames[]={\r\n");
            
            #line 26 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"

foreach (string name in ApplicationNames)
{

            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 30 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 31 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"

}

            
            #line default
            #line hidden
            this.Write("\t};\r\n\r\n\r\n");
            
            #line 37 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"

       foreach (ModelCppItem i in Items)
       {

            
            #line default
            #line hidden
            this.Write("#ifdef NODE_");
            
            #line 41 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.NodeId));
            
            #line default
            #line hidden
            this.Write("\r\n\r\neNodeID NODE = eNodeID::");
            
            #line 43 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.NodeId));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\r\n\r\nconst char MODEL::ModelString[] =\"");
            
            #line 47 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.ModelInfo));
            
            #line default
            #line hidden
            this.Write("\";\r\n}//end namespace\r\n#include <cModel_base.inc>\r\nnamespace sensact{\r\n\r\nconst eAp" +
                    "plicationID MODEL::NodeMasterApplication = eApplicationID::");
            
            #line 52 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.NodeId));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 54 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.StaticApplicationInitializers));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n\r\ncApplication *const MODEL::Glo2locCmd[] = {\r\n");
            
            #line 59 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.Glo2LocPointers));
            
            #line default
            #line hidden
            this.Write("\r\n};\r\n\r\n\r\n\r\ncApplication *const MODEL::Glo2locEvt[] = {\r\n");
            
            #line 65 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.Glo2LocEvents));
            
            #line default
            #line hidden
            this.Write("\r\n};\r\n#endif\r\n\r\n");
            
            #line 69 "C:\sensact\configware\Klli.Sensact.Config\Templates\HC_MODEL_CPP.tt"

           
       }

            
            #line default
            #line hidden
            this.Write("\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
